[package]
name = "nomos-sys"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
nomos-core = { path = "../nomos-core" }
serde.workspace = true
sysinfo.workspace = true
thiserror.workspace = true
tracing.workspace = true
nix.workspace = true
tokio.workspace = true
